### ISSUE TITLE
TypeError that occurs in IPython notebook but not IPython shell

### ISSUE THREAD

**Issue by kohaugustine** [ipython/ipynb#28]
Hi, I am posting this issue up here after having received zero help from Stackoverflow. I would greatly appreciate anyone's help on this!

[Cryptic TypeError: 'decimal.Decimal' object cannot be interpreted as an integer](http://stackoverflow.com/questions/42535279/cryptic-typeerror-decimal-decimal-object-cannot-be-interpreted-as-an-integer)

**Comment by Carreau** [comment]
San you check the value of `sys.executable` in both ?
Can you compare the values of sys.modules.keys() in both notebook and IPython ?
Are you a user of libraries like SymPy/Sage ? (I'm thinking the transformer that auto wrap numbers in AST )

The likely cause is an extension which is loaded only by ipykernel

**Comment by Carreau** [comment]
Check also the content of `~/.ipython/profile_default/ipython_kernel_config.py`

**Comment by kohaugustine** [comment]
Were you referring to this post from your repeated response to me on https://github.com/ipython/ipython/issues/10367 ? Sorry that I duplicated my question across these two repos...

**Comment by Carreau** [comment]
> Were you referring to this post from your repeated response to me on ipython/ipython#10367 ? Sorry that I duplicated my question across these two repos...

Ha yes ! thanks, closing here we can focus on the other one. GitHub still does miss some of my messages though.
